# Generated by Django 5.1.7 on 2025-04-15 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTextbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='streak',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('textbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.testtextbook')),
            ],
        ),
        migrations.CreateModel(
            name='Rag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textbook', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rag', to='core.testtextbook')),
            ],
        ),
    ]
