# Generated by Django 5.1.7 on 2025-03-22 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='created_at',
        ),
        migrations.AddField(
            model_name='test',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
