# Generated by Django 5.1.7 on 2025-04-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_testtextbook_profile_streak_testquestion_rag'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_test_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
