# Generated by Django 5.1.7 on 2025-04-15 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_last_test_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='last_test_day',
            new_name='last_test_date',
        ),
    ]
