# Generated by Django 5.1.7 on 2025-03-22 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_test_created_at_test_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='core.subject'),
        ),
    ]
