# Generated by Django 5.1.7 on 2025-03-22 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_question_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='question_data',
            field=models.TextField(default=''),
        ),
    ]
