# Generated by Django 5.1.7 on 2025-03-22 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_test_question_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='grade',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
