# Generated by Django 5.1.7 on 2025-03-22 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_test_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='due_date',
        ),
        migrations.AddField(
            model_name='test',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='question_data',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='test',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='core.subject'),
            preserve_default=False,
        ),
    ]
