# Generated by Django 5.1.7 on 2025-03-22 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_subject_description_remove_test_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='description',
        ),
    ]
