# Generated by Django 5.1.7 on 2025-04-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_first_name_profile_last_name_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='.../static/core/css/blank-profile-picture.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
