import openai
import PyPDF2
from django.shortcuts import render, redirect
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate
from django.contrib.auth.views import LoginView
from django.http import HttpResponse
from transformers import pipeline as transformers_pipeline
from .models import Test
from .forms import CustomUserCreationForm
import os
import logging
from .rag_model import RAGModel

# Initialize logger
logger = logging.getLogger(__name__)

# OpenAI API Key
openai.api_key = settings.OPENAI_API_KEY

rag_model = RAGModel()

def get_rag_model():
    """Initialize or return the RAG model."""
    # Add retrieval and generation pipeline logic here
    pass


def test_textbook_view(request):
    """View to display available textbooks."""
    media_path = settings.MEDIA_ROOT
    files = []

    # Fetch all PDF files in the media directory
    for root, dirs, filenames in os.walk(media_path):
        for file_name in filenames:
            if file_name.lower().endswith('.pdf'):
                relative_path = os.path.relpath(os.path.join(root, file_name), media_path)
                files.append({
                    'name': os.path.splitext(file_name)[0],
                    'url': f"{settings.MEDIA_URL}{relative_path.replace(os.sep, '/')}"
                })

    context = {'files': sorted(files, key=lambda x: x['name'])}
    return render(request, 'core/test_textbook.html', context)



def test_creation_view(request):
    """View to generate test questions from a selected PDF."""
    if request.method == 'POST':
        try:
            # Extract form data
            pdf_url = request.POST.get('pdf_url')
            start_page = int(request.POST.get('start_page', 0))
            end_page = int(request.POST.get('end_page', 0))

            # Validate form input
            if not pdf_url or start_page <= 0 or end_page <= 0 or start_page > end_page:
                raise ValueError("Invalid form data")

            # Load PDF content
            pdf_path = os.path.join(settings.MEDIA_ROOT, os.path.basename(pdf_url))
            with open(pdf_path, 'rb') as pdf_file:
                pdf_reader = PyPDF2.PdfReader(pdf_file)
                if start_page > len(pdf_reader.pages) or end_page > len(pdf_reader.pages):
                    raise ValueError("Page range exceeds the number of pages in the PDF.")

                # Extract text from the specified pages
                extracted_texts = [
                    pdf_reader.pages[page_num].extract_text()
                    for page_num in range(start_page - 1, end_page)
                ]

            # Use RAG model to generate questions
            questions = rag_model.generate_questions_from_pages(extracted_texts)
            if not questions:
                raise ValueError("No questions were generated by the RAG model.")

            # Store questions in session
            request.session['questions'] = questions
            request.session['current_question_index'] = 0

            return redirect('test_question')

        except Exception as e:
            logger.error(f"Error in test_creation_view: {e}")
            return redirect('test_textbook')

    return redirect('test_textbook')

def parse_generated_questions(generated_text):
    """Parse AI-generated text into structured questions."""
    questions = []
    for block in generated_text.split("\n\n"):
        lines = block.split("\n")
        if len(lines) < 5:
            continue
        question = lines[0]
        options = lines[1:5]
        correct_answer = lines[5].split(":")[1].strip() if len(lines) > 5 else None
        questions.append({
            'question': question,
            'options': options,
            'answer': correct_answer
        })
    return questions

def test_question_view(request):
    """View to display and handle test questions using minimal session writes."""
    # Retrieve questions and current index once, to minimize session access.
    questions = request.session.get('questions', [])
    current_question_index = request.session.get('current_question_index', 0)

    if request.method == 'POST':
        # Get the selected answer from POST data
        selected_answer = request.POST.get('selected_answer', '')

        # Get the current question once, and compute correctness.
        current_question = questions[current_question_index]
        correct_answer = current_question.get('answer', '')
        is_correct = (selected_answer == correct_answer)

        # Append only minimal data to results (avoid duplicating full question text/options)
        results = request.session.get('results', [])
        results.append({
            'selected_answer': selected_answer,
            'is_correct': is_correct
        })
        request.session['results'] = results

        # Increment and update current question index in session
        current_question_index += 1
        request.session['current_question_index'] = current_question_index

        # Redirect based on whether there are more questions
        if current_question_index < len(questions):
            return redirect('test_question')
        else:
            return redirect('test_result')

    else:
        # If it's a GET request, display the current question
        if current_question_index < len(questions):
            current_question = questions[current_question_index]
            context = {
                'question': current_question.get('question', ''),
                'answers': current_question.get('options', []),
                'current_question_index': current_question_index + 1,
                'total_questions': len(questions)
            }
            return render(request, 'core/test_question.html', context)
        else:
            return redirect('test_result')

def test_result_view(request):
    """View to display test results."""
    results = request.session.get('results', [])
    total_questions = len(results)
    correct_answers = sum(1 for result in results if result['is_correct'])
    wrong_answers_count = total_questions - correct_answers

    context = {
        'total_questions': total_questions,
        'correct_answers': correct_answers,
        'wrong_answers_count': wrong_answers_count,
        'results': results
    }
    return render(request, 'core/test_result.html', context)

@login_required
def profile_view(request):
    """View to display user profile and tests."""
    tests = Test.objects.all()
    context = {
        'username': request.user.username,
        'tests': tests,
    }
    return render(request, 'core/profile.html', context)

class CustomLoginView(LoginView):
    """Custom login view."""
    template_name = 'core/login.html'

    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(username=username, password=password)

        if user is not None:
            login(self.request, user)
            return super().form_valid(form)
        else:
            return HttpResponse("<h1>Invalid username or password</h1>")

    def get_success_url(self):
        return '/dashboard/'

def signup_view(request):
    """View to handle user signup."""
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('dashboard')
    else:
        form = CustomUserCreationForm()
    return render(request, 'core/signup.html', {'form': form})

def home_view(request):
    """Home view."""
    return render(request, 'base.html')

def dashboard_view(request):
    """Dashboard view."""
    if request.user.is_authenticated:
        context = {
            'username': request.user.username,
            'tests': Test.objects.all(),
        }
        return render(request, 'core/dashboard.html', context)
    else:
        return redirect('login')
    
def ranking_view(request):
    if request.method == 'GET':
        context = {
            'username': request.user.username,
            'rankings': [
                {'username': 'JohnDoe', 'score': 95},
                {'username': 'JaneSmith', 'score': 90},
                {'username': 'AliceBrown', 'score': 85},
            ]
        }
        return render(request, 'core/ranking.html', context)